/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trinkets_util_jni_JNIHelloWorldImpl */

#ifndef _Included_org_trinkets_util_jni_JNIHelloWorldImpl
#define _Included_org_trinkets_util_jni_JNIHelloWorldImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_trinkets_util_jni_JNIHelloWorldImpl
 * Method:    sayHello0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_trinkets_util_jni_JNIHelloWorldImpl_sayHello0
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
